version: "2"
services:
  db:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      EXTRA_CONF: "max_connections = 200"
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      timeout: 2s
    ports:
      - 5432:5432
    volumes:
      - postgredbdata:/var/lib/postgresql/data
volumes:
  postgredbdata:
